#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
- hosts: localhost
  #gather_facts: False
  roles:
    - role: gitconfig
      tags: gitconfig
    - role: openbox
      tags: openbox
    - role: user_scripts
      tags: user_scripts
    - role: user_symlink
      tags: user_symlink
    - role: ssh_config
      tags: ssh_config
