#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
- name: user_scripts | Get user home path
  shell: |
      export USERNAME=$(id -u -n) ;\
      export HOMEDIR=$(eval echo "~$(id -u -n)") ;\
      echo $HOMEDIR
  args:
    chdir: /home
    executable: /bin/bash
  register: user_symlink__r_user_home

- set_fact:
    ansible_user_home: "{{ user_symlink__r_user_home.stdout }}"

- name: user_scripts | Create dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_home }}/.local/bin"

- name: user_scripts | Copy files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_home }}/.local/bin/{{ item | basename }}"
    mode: +x
  loop: "{{ lookup('fileglob', role_path + '/files/*', wantlist=True) }}"
