#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
---
ansible_python_interpreter: "{{ playbook_dir }}/.python/bin/python"
ansible_connection: local
########################################################################
gitconfig__name: "Blinov Evgeniy"
gitconfig__email: evgeniy_blinov@mail.ru
